### ISSUE TITLE
Allow show_time_lag option for get_subscription_stats

### ISSUE THREAD

**Issue by larminen** [eiunkar/pyNakadi#10]
Nakadi API allows you to show consumer time lag. https://nakadi.io/manual.html#/subscriptions/subscription_id/stats_get

Its a simple url parameter that provides useful information in some usecases.

**Comment by eiunkarnewyorker** [comment]
Thanks for reporting. We may enhance the method with this parameter.

**Comment by eiunkar** [comment]
Thanks for reporting. We may enhance the method with this parameter.

**Comment by gizunkar** [comment]
I'll take over this

**Comment by eiunkar** [comment]
Solved.
