### ISSUE TITLE
Update event type leads to an Error

### ISSUE THREAD

**Issue by max-neverov** [eiunkar/pyNakadi#14]
**Describe the bug**
Nakadi [event-type PUT endpoint ](https://nakadi.io/manual.html#/event-types/name_put) returns empty string. Client update_event_type method [tries to convert empty string to JSON](https://github.com/eiunkar/pyNakadi/blob/master/pyNakadi/client.py#L243) and fails since it's not a valid JSON.

**To Reproduce**
1. Make a valid PUT request to Nakadi event-types endpoint (client.update_event_type(...)) 
2. See error
```
  File "/usr/local/lib/python3.6/dist-packages/pyNakadi/client.py", line 256, in update_event_type
    result_map = json.loads(response_content_str)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Expected behavior**
No error

**Comment by max-neverov** [comment]
@eiunkar please take a look [to the fix.](https://github.com/eiunkar/pyNakadi/pull/15)

**Comment by eiunkar** [comment]
Merged.
