### ISSUE TITLE
Add Documentation on subscription

### ISSUE THREAD

**Issue by KonMann** [eiunkar/pyNakadi#2]
It would be nice to have some documentation on how to subscribe to topics and consume events with some examples

**Comment by dmigo** [comment]
Do you have any experience with that?

**Comment by KonMann** [comment]
Writing documentation?

**Comment by dmigo** [comment]
Subscribing to events using `pyNakadi`, I'm asking cause i'm starting with it.

**Comment by KonMann** [comment]
I have not used this library so far (we wrote our own), but would very much like to do.

**Comment by dmigo** [comment]
@KonMann please feel free to comment/edit the pr
